### ISSUE TITLE
Improvement about Coherences and Multi-channels 

### ISSUE THREAD

**Issue by YongyuG** [andreas12345/cdr-dereverb#1]
Dear Andreas,

Thanks for your works, it does help me a lot for dereverberation and CDR.

I have two questions about CDR and your paper.

1. The noise coherence estimation from your paper is fixed, which is an ideal case. But in reality, the noise coherence will change along with different environments I believe, are there any other methodologies for improving that?

2. The paper for estimating CDR is only for 2-microphones. If I want to do multi-channels such as 8mics, do you have better way in maths to compute multi-channels(>2mics) CDR

Regards
Yongyu

**Comment by andreas12345** [comment]
Hi,

1. the diffuse coherence is a pretty good approximation for most rooms. But it should also be possible to implement an online tracking of the noise coherence, e.g., by using a voice activity detector and estimating the coherence in noise-only segments.

2. You could simply compute the CDR from multiple microphone pairs in the array and use the average. Alternatively, you can use a maximum likelihood estimator for direct and diffuse power, which has a closed-form solution (assuming the noise coherence and direction of arrival is known): https://uol.de/fileadmin/user_upload/mediphysik/ag/sigproc/download/papers/SP2015_42.pdf

- Andreas
