### ISSUE TITLE
p vlaue problem??????

### ISSUE THREAD

**Issue by Bshbhs** [andreas12345/cdr-dereverb#3]
Thank you for the great work, I would just like to ask about the function of [p=IterLSDesign(cfg.Lp,cfg.K,cfg.N);] it is not available in the code, and I wonder how you get the value of p?. Also, do I need to calculate this p value if I will use a different wave file?. Is it ok to use the p value that you're using in the code to run other audio wave files?

**Comment by andreas12345** [comment]
Hi, p is the prototype filter response of the filterbank. It is loaded from the included .mat file, therefore the line assigning p is commented out in the demo code. If you want to run the design function yourself, you can find copies of IterLSDesign.m in various places on the web and on github (it used to be available on Stefan Weiss' website, but that seems to have disappeared).
